name: translation-sync
env:
  USER_NAME: hirotaka
  USER_EMAIL: 52546+hirotaka@users.noreply.github.com
  GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
on:
  schedule:
    - cron:  '15 21 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run sync command
        run: npm run sync
