name: translation-sync
env:
  USER_NAME: hirotaka
  USER_EMAIL: hello@stackhacker.io
  GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
on:
  schedule:
    - cron:  '15 21 * * *'

jobs:
  sync:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 14.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run sync command
        run: npm run sync
